#include "app_config.h"
#include "audio_config.h"
#include "tone_player.h"

const char *tone_table[] = {
    [IDEX_TONE_NUM_0] 			= TONE_NUM_0,
    [IDEX_TONE_NUM_1] 			= TONE_NUM_1,
    [IDEX_TONE_NUM_2] 			= TONE_NUM_2,
    [IDEX_TONE_NUM_3] 			= TONE_NUM_3,
    [IDEX_TONE_NUM_4] 			= TONE_NUM_4,
    [IDEX_TONE_NUM_5] 			= TONE_NUM_5,
    [IDEX_TONE_NUM_6] 			= TONE_NUM_6,
    [IDEX_TONE_NUM_7] 			= TONE_NUM_7,
    [IDEX_TONE_NUM_8] 			= TONE_NUM_8,
    [IDEX_TONE_NUM_9] 			= TONE_NUM_9,
    [IDEX_TONE_BT_MODE] 		= TONE_BT_MODE,
    [IDEX_TONE_BT_CONN] 		= TONE_BT_CONN,
    [IDEX_TONE_BT_DISCONN] 		= TONE_BT_DISCONN,
    [IDEX_TONE_TWS_CONN] 		= TONE_TWS_CONN,
    [IDEX_TONE_TWS_DISCONN]		= TONE_TWS_DISCONN,
    [IDEX_TONE_LOW_POWER] 		= TONE_LOW_POWER,
    [IDEX_TONE_POWER_OFF] 		= TONE_POWER_OFF,
    [IDEX_TONE_POWER_ON] 		= TONE_POWER_ON,
    [IDEX_TONE_RING] 			= TONE_RING,
    [IDEX_TONE_MAX_VOL] 		= TONE_MAX_VOL,
    [IDEX_TONE_NORMAL] 			= TONE_NORMAL,
    [IDEX_TONE_MUSIC] 			= TONE_MUSIC,
    [IDEX_TONE_LINEIN] 			= TONE_LINEIN,
    [IDEX_TONE_FM] 				= TONE_FM,
    [IDEX_TONE_PC] 				= TONE_PC,
    [IDEX_TONE_RTC] 			= TONE_RTC,
    [IDEX_TONE_RECORD] 			= TONE_RECORD,
    [IDEX_TONE_UDISK] 			= TONE_RES_ROOT_PATH"tone/udisk.*",
    [IDEX_TONE_SD] 				= TONE_RES_ROOT_PATH"tone/sd.*",

    // 用户提示音：共122个（包含复用/节日/生日/人声模拟）
    // 规则：IDEX_TONE_USER_001 -> tone0.*，依次递增
    [IDEX_TONE_USER_001]        = TONE_RES_ROOT_PATH"tone/tone0.*",
    [IDEX_TONE_USER_002]        = TONE_RES_ROOT_PATH"tone/tone1.*",
    [IDEX_TONE_USER_003]        = TONE_RES_ROOT_PATH"tone/tone2.*",
    [IDEX_TONE_USER_004]        = TONE_RES_ROOT_PATH"tone/tone3.*",
    [IDEX_TONE_USER_005]        = TONE_RES_ROOT_PATH"tone/tone4.*",
    [IDEX_TONE_USER_006]        = TONE_RES_ROOT_PATH"tone/tone5.*",
    [IDEX_TONE_USER_007]        = TONE_RES_ROOT_PATH"tone/tone6.*",
    [IDEX_TONE_USER_008]        = TONE_RES_ROOT_PATH"tone/tone7.*",
    [IDEX_TONE_USER_009]        = TONE_RES_ROOT_PATH"tone/tone8.*",
    [IDEX_TONE_USER_010]        = TONE_RES_ROOT_PATH"tone/tone9.*",
    [IDEX_TONE_USER_011]        = TONE_RES_ROOT_PATH"tone/tone10.*",
    [IDEX_TONE_USER_012]        = TONE_RES_ROOT_PATH"tone/tone11.*",
    [IDEX_TONE_USER_013]        = TONE_RES_ROOT_PATH"tone/tone12.*",
    [IDEX_TONE_USER_014]        = TONE_RES_ROOT_PATH"tone/tone13.*",
    [IDEX_TONE_USER_015]        = TONE_RES_ROOT_PATH"tone/tone14.*",
    [IDEX_TONE_USER_016]        = TONE_RES_ROOT_PATH"tone/tone15.*",
    [IDEX_TONE_USER_017]        = TONE_RES_ROOT_PATH"tone/tone16.*",
    [IDEX_TONE_USER_018]        = TONE_RES_ROOT_PATH"tone/tone17.*",
    [IDEX_TONE_USER_019]        = TONE_RES_ROOT_PATH"tone/tone18.*",
    [IDEX_TONE_USER_020]        = TONE_RES_ROOT_PATH"tone/tone19.*",
    [IDEX_TONE_USER_021]        = TONE_RES_ROOT_PATH"tone/tone20.*",
    [IDEX_TONE_USER_022]        = TONE_RES_ROOT_PATH"tone/tone21.*",
    [IDEX_TONE_USER_023]        = TONE_RES_ROOT_PATH"tone/tone22.*",
    [IDEX_TONE_USER_024]        = TONE_RES_ROOT_PATH"tone/tone23.*",
    [IDEX_TONE_USER_025]        = TONE_RES_ROOT_PATH"tone/tone24.*",
    [IDEX_TONE_USER_026]        = TONE_RES_ROOT_PATH"tone/tone25.*",
    [IDEX_TONE_USER_027]        = TONE_RES_ROOT_PATH"tone/tone26.*",
    [IDEX_TONE_USER_028]        = TONE_RES_ROOT_PATH"tone/tone27.*",

    [IDEX_TONE_USER_029]        = TONE_RES_ROOT_PATH"tone/tone28.*",
    [IDEX_TONE_USER_030]        = TONE_RES_ROOT_PATH"tone/tone29.*",
    [IDEX_TONE_USER_031]        = TONE_RES_ROOT_PATH"tone/tone30.*",
    [IDEX_TONE_USER_032]        = TONE_RES_ROOT_PATH"tone/tone31.*",
    [IDEX_TONE_USER_033]        = TONE_RES_ROOT_PATH"tone/tone32.*",
    [IDEX_TONE_USER_034]        = TONE_RES_ROOT_PATH"tone/tone33.*",
    [IDEX_TONE_USER_035]        = TONE_RES_ROOT_PATH"tone/tone34.*",
    [IDEX_TONE_USER_036]        = TONE_RES_ROOT_PATH"tone/tone35.*",
    [IDEX_TONE_USER_037]        = TONE_RES_ROOT_PATH"tone/tone36.*",
    [IDEX_TONE_USER_038]        = TONE_RES_ROOT_PATH"tone/tone37.*",
    [IDEX_TONE_USER_039]        = TONE_RES_ROOT_PATH"tone/tone38.*",
    [IDEX_TONE_USER_040]        = TONE_RES_ROOT_PATH"tone/tone39.*",
    [IDEX_TONE_USER_041]        = TONE_RES_ROOT_PATH"tone/tone40.*",
    [IDEX_TONE_USER_042]        = TONE_RES_ROOT_PATH"tone/tone41.*",
    [IDEX_TONE_USER_043]        = TONE_RES_ROOT_PATH"tone/tone42.*",
    [IDEX_TONE_USER_044]        = TONE_RES_ROOT_PATH"tone/tone43.*",
    [IDEX_TONE_USER_045]        = TONE_RES_ROOT_PATH"tone/tone44.*",
    [IDEX_TONE_USER_046]        = TONE_RES_ROOT_PATH"tone/tone45.*",
    [IDEX_TONE_USER_047]        = TONE_RES_ROOT_PATH"tone/tone46.*",
    [IDEX_TONE_USER_048]        = TONE_RES_ROOT_PATH"tone/tone47.*",
    [IDEX_TONE_USER_049]        = TONE_RES_ROOT_PATH"tone/tone48.*",
    [IDEX_TONE_USER_050]        = TONE_RES_ROOT_PATH"tone/tone49.*",
    [IDEX_TONE_USER_051]        = TONE_RES_ROOT_PATH"tone/tone50.*",
    [IDEX_TONE_USER_052]        = TONE_RES_ROOT_PATH"tone/tone51.*",
    [IDEX_TONE_USER_053]        = TONE_RES_ROOT_PATH"tone/tone52.*",
    [IDEX_TONE_USER_054]        = TONE_RES_ROOT_PATH"tone/tone53.*",
    [IDEX_TONE_USER_055]        = TONE_RES_ROOT_PATH"tone/tone54.*",
    [IDEX_TONE_USER_056]        = TONE_RES_ROOT_PATH"tone/tone55.*",

    [IDEX_TONE_USER_057]        = TONE_RES_ROOT_PATH"tone/tone56.*",
    [IDEX_TONE_USER_058]        = TONE_RES_ROOT_PATH"tone/tone57.*",
    [IDEX_TONE_USER_059]        = TONE_RES_ROOT_PATH"tone/tone58.*",
    [IDEX_TONE_USER_060]        = TONE_RES_ROOT_PATH"tone/tone59.*",
    [IDEX_TONE_USER_061]        = TONE_RES_ROOT_PATH"tone/tone60.*",
    [IDEX_TONE_USER_062]        = TONE_RES_ROOT_PATH"tone/tone61.*",
    [IDEX_TONE_USER_063]        = TONE_RES_ROOT_PATH"tone/tone62.*",
    [IDEX_TONE_USER_064]        = TONE_RES_ROOT_PATH"tone/tone63.*",
    [IDEX_TONE_USER_065]        = TONE_RES_ROOT_PATH"tone/tone64.*",
    [IDEX_TONE_USER_066]        = TONE_RES_ROOT_PATH"tone/tone65.*",
    [IDEX_TONE_USER_067]        = TONE_RES_ROOT_PATH"tone/tone66.*",
    [IDEX_TONE_USER_068]        = TONE_RES_ROOT_PATH"tone/tone67.*",
    [IDEX_TONE_USER_069]        = TONE_RES_ROOT_PATH"tone/tone68.*",
    [IDEX_TONE_USER_070]        = TONE_RES_ROOT_PATH"tone/tone69.*",
    [IDEX_TONE_USER_071]        = TONE_RES_ROOT_PATH"tone/tone70.*",
    [IDEX_TONE_USER_072]        = TONE_RES_ROOT_PATH"tone/tone71.*",
    [IDEX_TONE_USER_073]        = TONE_RES_ROOT_PATH"tone/tone72.*",
    [IDEX_TONE_USER_074]        = TONE_RES_ROOT_PATH"tone/tone73.*",
    [IDEX_TONE_USER_075]        = TONE_RES_ROOT_PATH"tone/tone74.*",
    [IDEX_TONE_USER_076]        = TONE_RES_ROOT_PATH"tone/tone75.*",
    [IDEX_TONE_USER_077]        = TONE_RES_ROOT_PATH"tone/tone76.*",
    [IDEX_TONE_USER_078]        = TONE_RES_ROOT_PATH"tone/tone77.*",
    [IDEX_TONE_USER_079]        = TONE_RES_ROOT_PATH"tone/tone78.*",
    [IDEX_TONE_USER_080]        = TONE_RES_ROOT_PATH"tone/tone79.*",
    [IDEX_TONE_USER_081]        = TONE_RES_ROOT_PATH"tone/tone80.*",
    [IDEX_TONE_USER_082]        = TONE_RES_ROOT_PATH"tone/tone81.*",
    [IDEX_TONE_USER_083]        = TONE_RES_ROOT_PATH"tone/tone82.*",
    [IDEX_TONE_USER_084]        = TONE_RES_ROOT_PATH"tone/tone83.*",

    [IDEX_TONE_USER_085]        = TONE_RES_ROOT_PATH"tone/tone84.*",
    [IDEX_TONE_USER_086]        = TONE_RES_ROOT_PATH"tone/tone85.*",
    [IDEX_TONE_USER_087]        = TONE_RES_ROOT_PATH"tone/tone86.*",
    [IDEX_TONE_USER_088]        = TONE_RES_ROOT_PATH"tone/tone87.*",
    [IDEX_TONE_USER_089]        = TONE_RES_ROOT_PATH"tone/tone88.*",
    [IDEX_TONE_USER_090]        = TONE_RES_ROOT_PATH"tone/tone89.*",
    [IDEX_TONE_USER_091]        = TONE_RES_ROOT_PATH"tone/tone90.*",
    [IDEX_TONE_USER_092]        = TONE_RES_ROOT_PATH"tone/tone91.*",
    [IDEX_TONE_USER_093]        = TONE_RES_ROOT_PATH"tone/tone92.*",
    [IDEX_TONE_USER_094]        = TONE_RES_ROOT_PATH"tone/tone93.*",
    [IDEX_TONE_USER_095]        = TONE_RES_ROOT_PATH"tone/tone94.*",
    [IDEX_TONE_USER_096]        = TONE_RES_ROOT_PATH"tone/tone95.*",
    [IDEX_TONE_USER_097]        = TONE_RES_ROOT_PATH"tone/tone96.*",
    [IDEX_TONE_USER_098]        = TONE_RES_ROOT_PATH"tone/tone97.*",
    [IDEX_TONE_USER_099]        = TONE_RES_ROOT_PATH"tone/tone98.*",

    [IDEX_TONE_USER_100]        = TONE_RES_ROOT_PATH"tone/tone99.*",
    [IDEX_TONE_USER_101]        = TONE_RES_ROOT_PATH"tone/tone100.*",
    [IDEX_TONE_USER_102]        = TONE_RES_ROOT_PATH"tone/tone101.*",
    [IDEX_TONE_USER_103]        = TONE_RES_ROOT_PATH"tone/tone102.*",
    [IDEX_TONE_USER_104]        = TONE_RES_ROOT_PATH"tone/tone103.*",
    [IDEX_TONE_USER_105]        = TONE_RES_ROOT_PATH"tone/tone104.*",
    [IDEX_TONE_USER_106]        = TONE_RES_ROOT_PATH"tone/tone105.*",
    [IDEX_TONE_USER_107]        = TONE_RES_ROOT_PATH"tone/tone106.*",

    [IDEX_TONE_USER_108]        = TONE_RES_ROOT_PATH"tone/tone107.*",

    [IDEX_TONE_USER_109]        = TONE_RES_ROOT_PATH"tone/tone108.*",
    [IDEX_TONE_USER_110]        = TONE_RES_ROOT_PATH"tone/tone109.*",
    [IDEX_TONE_USER_111]        = TONE_RES_ROOT_PATH"tone/tone110.*",
    [IDEX_TONE_USER_112]        = TONE_RES_ROOT_PATH"tone/tone111.*",
    [IDEX_TONE_USER_113]        = TONE_RES_ROOT_PATH"tone/tone112.*",
    [IDEX_TONE_USER_114]        = TONE_RES_ROOT_PATH"tone/tone113.*",
    [IDEX_TONE_USER_115]        = TONE_RES_ROOT_PATH"tone/tone114.*",
    [IDEX_TONE_USER_116]        = TONE_RES_ROOT_PATH"tone/tone115.*",
    [IDEX_TONE_USER_117]        = TONE_RES_ROOT_PATH"tone/tone116.*",
    [IDEX_TONE_USER_118]        = TONE_RES_ROOT_PATH"tone/tone117.*",
    [IDEX_TONE_USER_119]        = TONE_RES_ROOT_PATH"tone/tone118.*",
    [IDEX_TONE_USER_120]        = TONE_RES_ROOT_PATH"tone/tone119.*",
    [IDEX_TONE_USER_121]        = TONE_RES_ROOT_PATH"tone/tone120.*",
    [IDEX_TONE_USER_122]        = TONE_RES_ROOT_PATH"tone/tone121.*",
    

    //testmusic
    [IDEX_TONE_USER_123]        = TONE_RES_ROOT_PATH"tone/test11111.*",
    
};

const int tone_table_size = sizeof(tone_table) / sizeof(tone_table[0]);
